### ISSUE TITLE
SQLAlchemy version

### ISSUE THREAD

**Issue by MadeByLR** [MadeByLR/To-Do-List#1]
When I was running my python app app.py, I was receiving the error message: 

Traceback (most recent call last):
  File "/Users/lrs/Documents/Projects/Flask_Python/To-Do-List/app.py", line 7, in <module>
    db = SQLAlchemy(app)
         ^^^^^^^^^^^^^^^
  File "/Users/lrs/Documents/Projects/Flask_Python/To-Do-List/venv/lib/python3.11/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
    _include_sqlalchemy(self, query_class)
  File "/Users/lrs/Documents/Projects/Flask_Python/To-Do-List/venv/lib/python3.11/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
    for key in module.__all__:
               ^^^^^^^^^^^^^^
AttributeError: module 'sqlalchemy' has no attribute '__all__'. Did you mean: '__file__'?

**Comment by MadeByLR** [comment]
This was related to the version that was being used, the video on you suggested to use 2.5.1 which still gave the same error, tried 2.5.0 but still did not work. Tried a few suggestions from ChatGPT to uninstall and reinstall SQLAlchemy but then tried version pip install SQLAlchemy==1.4.23 this now runs without the error and the file db.sqlite creates.

**Comment by MadeByLR** [comment]
This was related to the version that was being used, the video on you suggested to use 2.5.1 which still gave the same error, tried 2.5.0 but still did not work. Tried a few suggestions from ChatGPT to uninstall and reinstall SQLAlchemy but then tried version pip install SQLAlchemy==1.4.23 this now runs without the error and the file db.sqlite creates.
